import NavBar from "./Components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex w-screen   text-white`}>
        <div className="md:w-[21%] ">
          <NavBar />
        </div>
        <div className="md:w-[79%] bg-black ">{children}</div>
      </body>
    </html>
  );
}
